# Generated by Django 2.2.7 on 2019-11-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191121_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bad_count',
            field=models.IntegerField(default=0, verbose_name='差评数'),
        ),
        migrations.AddField(
            model_name='post',
            name='good_count',
            field=models.IntegerField(default=0, verbose_name='好评数'),
        ),
    ]
